repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.12.2
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/jazzband/pip-tools
    rev: v6.4.0
    hooks:
      - id: pip-compile
        args: [--upgrade]

  - repo: local
    hooks:
      - id: pip-review
        name: pip-review
        entry: pip-review --auto
        language: system
        files: ^requirements\.txt$
        stages: [commit]

      - id: update-pyproject-toml
        name: update-pyproject-toml
        entry: pip-review --auto && git add pyproject.toml
        language: system
        files: ^pyproject\.toml$
        stages: [commit]
